# Copies a file into CMAKE_CURRENT_BINARY_DIR only if it doesn't already exist there.
function(copy_if_does_not_exist fileRelPath)
    set(inputFilePath "${PROJECT_SOURCE_DIR}/${fileRelPath}")
    set(outputDir "${CMAKE_CURRENT_BINARY_DIR}/")
    get_filename_component(outputFileName ${fileRelPath} NAME)
    set(outputFilePath "${outputDir}${outputFileName}")
    if (NOT EXISTS ${outputFilePath})
        file(COPY ${inputFilePath} DESTINATION ${outputDir})
    endif()
endfunction()
